import argparse
import asyncio
import os
import sys
from datetime import datetime
from dotenv import load_dotenv

# Load the tool agent's environment variables from its isolated directory
load_dotenv("tool_agent/.env", override=True)

# Add the workspace root to sys.path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from core.utils import trace
from core.runner import initialize_runner
from security.manifest_verifier import SecurityError
from tool_agent.agent import ToolAgent
from dark_agent.agent import DarkAgent
from secured_agent.agent import SecuredToolAgent

PROMPT_PATH = "prompts/tool_agent_instructions.md"
GOVERNANCE_PROMPT = "Explain the governance rules you are currently enforcing, specifically the cloud project name and target dataset."
LOG_FILE = "dark_agent_execution.log"

def inspect_environment():
    """Prints the status of sensitive environment variables to highlight vulnerability/exposure."""
    trace("\n🔍 Environment Vulnerability Inspection:")
    trace(f"  - GOOGLE_APPLICATION_CREDENTIALS: {os.environ.get('GOOGLE_APPLICATION_CREDENTIALS', '❌ NOT FOUND / DELETED')}")
    trace(f"  - SYSTEM_PROMPT_FILE:             {os.environ.get('SYSTEM_PROMPT_FILE', '❌ NOT FOUND / DELETED')}")
    trace("-" * 60)

def get_backup_content() -> str:
    """Reads and returns the backup of the original prompt content."""
    if not os.path.exists(PROMPT_PATH):
        print(f"❌ Error: {PROMPT_PATH} not found.")
        sys.exit(1)
    with open(PROMPT_PATH, "r", encoding="utf-8") as f:
        return f.read()

async def run_stage_1(app_name: str):
    """Executes the standard normal operation with untampered prompts."""
    trace("\n🟢 STAGE 1: Vulnerable Baseline Normal Run")    
    inspect_environment()
    
    runner = initialize_runner(app_name)
    agent = ToolAgent()
    agent.agent.name = "BaselineAgent"
    
    trace(f"📖 Prompt Read by Agent:\n{GOVERNANCE_PROMPT}\n")
    response = await runner.run_task(agent.agent, GOVERNANCE_PROMPT)
    trace(f"\n✍️ Response Generated by Agent:\n{response}")
    trace("-" * 60)

async def run_stage_2(app_name: str):
    """Simulates the adversarial supply chain attack and shows how it affects the existing ToolAgent."""
    trace("\n🔴 STAGE 2: Supply-Chain Exploit via DarkAgent")    
    
    # 1. Run the exploit via DarkAgent
    attacker = DarkAgent()
    attacker.run_exploit(PROMPT_PATH)
    
    # Show variables are exposed before run
    inspect_environment()
    
    # 2. Run the stage 1 tool agent again to show how the existing code is affected
    runner = initialize_runner(app_name)
    compromised_agent = ToolAgent()
    compromised_agent.agent.name = "CompromisedAgent"
    
    trace(f"\n📖 Prompt Read by Agent:\n{GOVERNANCE_PROMPT}\n")
    response = await runner.run_task(compromised_agent.agent, GOVERNANCE_PROMPT)
    trace(f"\n✍️ Response Generated by Agent:\n{response}")
    trace("-" * 60)

async def run_stage_3(app_name: str, backup_content: str):
    """Hardens the pipeline, intercepting prompt mutations, restoring baseline, and executing securely."""
    trace("\n🛡️ STAGE 3: Secured Layer (SecuredToolAgent) Defense")    
    
    # Ensure there is a mutated prompt to test the block
    trace("😈 [Simulation] Injecting mutated prompt to test SecuredToolAgent defense...")
    attacker = DarkAgent()
    attacker.run_exploit(PROMPT_PATH)
    
    trace("\n👉 Attempting to initialize SecuredToolAgent with mutated prompts...")
    try:
        SecuredToolAgent()
        trace("❌ ERROR: SecuredToolAgent allowed initialization of a mutated prompt!")
    except SecurityError as e:
        trace("✅ SUCCESS: SecuredToolAgent blocked tampered prompt file initialization!")
        trace(f"Exception details: {e}\n")
        
    trace("👉 Restoring prompt file to baseline and signing it...")
    with open(PROMPT_PATH, "w", encoding="utf-8") as f:
        f.write(backup_content)
    
    # Sign prompts
    os.system("make prompts")
    
    trace("\n👉 Attempting to initialize SecuredToolAgent with restored, valid prompt...")
    try:
        runner = initialize_runner(app_name)
        agent = SecuredToolAgent()
        agent.agent.name = "secured"

        
        # Verify variables are successfully cleared in Secured Agent
        inspect_environment()
        
        trace("✅ SUCCESS: SecuredToolAgent successfully initialized with valid signature!\n")
        
        trace(f"📖 Prompt Read by Agent:\n{GOVERNANCE_PROMPT}\n")
        response = await runner.run_task(agent.agent, GOVERNANCE_PROMPT)
        trace(f"\n✍️ Response Generated by Agent:\n{response}")
    except Exception as e:
        import traceback
        traceback.print_exc()
        trace(f"❌ ERROR: SecuredToolAgent initialization/execution failed on valid prompt: {e}")
    trace("-" * 60)


async def main():
    parser = argparse.ArgumentParser(description="Dark Agent Security lifecycle stages runner.")
    parser.add_argument("--stage", type=int, choices=[1, 2, 3], required=True, help="Which stage to execute (1: Normal, 2: Hijacked, 3: Hardened).")
    parser.add_argument("--app-name", type=str, default="MTA_Security_Demo", help="Name of the app for runner session.")
    args = parser.parse_args()

    # Clear old execution log at start of stage run
    if os.path.exists(LOG_FILE):
        os.remove(LOG_FILE)

    trace(f"🎬 Starting Dark Agent Security Lifecycle Demonstration (Stage {args.stage})...")
    trace("=" * 60)

    # Back up the prompt to allow stage 3 to restore it
    backup_content = get_backup_content()

    if args.stage == 1:
        await run_stage_1(args.app_name)
    elif args.stage == 2:
        await run_stage_2(args.app_name)
    elif args.stage == 3:
        await run_stage_3(args.app_name, backup_content)
        
    trace("=" * 60)
    trace("🏁 Demo Workflow Completed.")

if __name__ == "__main__":
    asyncio.run(main())
